In [32]:
#importing libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [33]:
#load dataset
df=pd.read_csv(r"C:\Users\pranj\Downloads\Credit card transactions - India - Simple.csv")

In [34]:
df

,index,City,Date,Card Type,Exp Type,Gender,Amount
0,0,"Delhi, India",29-Oct-14,Gold,Bills,F,82475
1,1,"Greater Mumbai, India",22-Aug-14,Platinum,Bills,F,32555
2,2,"Bengaluru, India",27-Aug-14,Silver,Bills,F,101738
3,3,"Greater Mumbai, India",12-Apr-14,Signature,Bills,F,123424
4,4,"Bengaluru, India",5-May-15,Gold,Bills,F,171574
...,...,...,...,...,...,...,...
26047,26047,"Kolkata, India",22-Jun-14,Silver,Travel,F,128191
26048,26048,"Pune, India",3-Aug-14,Signature,Travel,M,246316
26049,26049,"Hyderabad, India",16-Jan-15,Silver,Travel,M,265019
26050,26050,"Kanpur, India",14-Sep-14,Silver,Travel,M,88174
26051,26051,"Hyderabad, India",19-Oct-13,Signature,Bills,M,184410

In [35]:
df.describe()

              index         Amount
count  26052.000000   26052.000000
mean   13025.500000  156411.537425
std     7520.708943  103063.254287
min        0.000000    1005.000000
25%     6512.750000   77120.250000
50%    13025.500000  153106.500000
75%    19538.250000  228050.000000
max    26051.000000  998077.000000

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26052 entries, 0 to 26051
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      26052 non-null  int64
 1   City       26052 non-null  object
 2   Date       26052 non-null  object
 3   Card Type  26052 non-null  object
 4   Exp Type   26052 non-null  object
 5   Gender     26052 non-null  object
 6   Amount     26052 non-null  int64
dtypes: int64(2), object(5)
memory usage: 1.4+ MB

In [37]:
#importing libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [38]:
import warnings
warnings.filterwarnings("ignore")
#convert date column
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year
df = df.drop('Date', axis=1)

In [39]:
df

,index,City,Card Type,Exp Type,Gender,Amount,Month,Year
0,0,"Delhi, India",Gold,Bills,F,82475,10,2014
1,1,"Greater Mumbai, India",Platinum,Bills,F,32555,8,2014
2,2,"Bengaluru, India",Silver,Bills,F,101738,8,2014
3,3,"Greater Mumbai, India",Signature,Bills,F,123424,4,2014
4,4,"Bengaluru, India",Gold,Bills,F,171574,5,2015
...,...,...,...,...,...,...,...,...
26047,26047,"Kolkata, India",Silver,Travel,F,128191,6,2014
26048,26048,"Pune, India",Signature,Travel,M,246316,8,2014
26049,26049,"Hyderabad, India",Silver,Travel,M,265019,1,2015
26050,26050,"Kanpur, India",Silver,Travel,M,88174,9,2014
26051,26051,"Hyderabad, India",Signature,Bills,M,184410,10,2013

In [40]:
#Encode Categorical Columns
le = LabelEncoder()

df['City'] = le.fit_transform(df['City'])
df['Card Type'] = le.fit_transform(df['Card Type'])
df['Exp Type'] = le.fit_transform(df['Exp Type'])
df['Gender'] = le.fit_transform(df['Gender'])

In [41]:
df = df.drop('index', axis=1)

In [42]:
df

       City  Card Type  Exp Type  Gender  Amount  Month  Year
0       126          0         0       0   82475     10  2014
1       170          1         0       0   32555      8  2014
2        71          3         0       0  101738      8  2014
3       170          2         0       0  123424      4  2014
4        71          0         0       0  171574      5  2015
...     ...        ...       ...     ...     ...    ...   ...
26047   267          3         5       0  128191      6  2014
26048   584          2         5       1  246316      8  2014
26049   193          3         5       1  265019      1  2015
26050   237          3         5       1   88174      9  2014
26051   193          2         0       1  184410     10  2013

[26052 rows x 7 columns]

In [43]:
df['Preferable'] = (df['Amount'] > df['Amount'].mean()).astype(int)
#Create Target Variable,If Amount > average amount, we say card usage is Good (1) otherwise Not Good (0).

In [44]:
#defining feature and target
X = df.drop('Preferable', axis=1)
y = df['Preferable']

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)
#train_test_split

In [46]:
model = RandomForestClassifier()
#model train
model.fit(X_train, y_train)

RandomForestClassifier()

In [47]:
#prediction
y_pred = model.predict(X_test)

In [48]:
#checking accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [49]:
sample = [[1,2,0,1,5000,5,2024]]
prediction = model.predict(sample)

if prediction == 1:
    print("This card is preferable")
else:
    print("This card is not preferable")

This card is not preferable